### ISSUE TITLE
Want to talk to you

### ISSUE THREAD

**Issue by manishkumar1601** [TOXIC-DEVIL/WhatsAsenaPublic#4]
hello bro i dont have any contact of you thatswhy i created issue here i want to talk to you i have a whatsapp bot its about that please send you instagram or whatsapp number so i can message you, my instagram is @vminkook_manish

**Comment by TOXIC-DEVIL** [comment]
> hello bro i dont have any contact of you thatswhy i created issue here i want to talk to you i have a whatsapp bot its about that please send you instagram or whatsapp number so i can message you, my instagram is @vminkook_manish

Sure, You can contact me here :- https://www.instagram.com/phycoyude___chunk_____/
