### ISSUE TITLE
TO ADD A FEATURE...

### ISSUE THREAD

**Issue by anirudhsudheer** [TOXIC-DEVIL/WhatsAsenaPublic#5]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by anirudhsudheer** [comment]
HEYBRO,

PLEASE ADD THE A BRODCAST FEATURE..

**Comment by TOXIC-DEVIL** [comment]
> HEYBRO,
> 
> PLEASE ADD THE A BRODCAST FEATURE..

Hey anirudhsudheer,

We Will Start Working On It As Soon as Possible. Thanks For This Command & We Will Add It In This Ropo.

          -- TOXIC DEVIL ❤

**Comment by ak-kaddu** [comment]
Can you please add a cricket score feature

**Comment by TOXIC-DEVIL** [comment]
> Can you please add a cricket score feature

Hey User!! 👋
We Can't add that feature here because its a helper bot only, if possible we will make a bot for that 😁

🐺 Thank You For Requesting a Command 💕
                                 -- TOXIC-DEVIL
