### ISSUE TITLE
QR scan error and too many vulurablities

### ISSUE THREAD

**Issue by satyammayy** [TOXIC-DEVIL/WhatsAsenaPublic#7]
please help bro

**Comment by TOXIC-DEVIL** [comment]
> please help bro

Hey User!! 😍
Did you mean the baileys problem?
We have fixed that on our ropo and please install the new version of baileys on your termux and try qr code again ☺️

Please Use on Termux :

git clone https://github.com/TOXIC-DEVIL/WhatsAsenaPublic

cd WhatsAsenaPublic

npm i @adiwajshing/baileys

npm i chalk

node qr.js

To upgrade baileys version and to get qr code 👋

Thank You For Reporting Us 💕
